---
  #
  # list OS X Defaults you want toggled here.
  #
  # Example:
  # -
  #   domain: "com.confkit.framer"
  #   section: "DeveloperMenu"
  #   type: "-bool"
  #   value: "true"
  #
  # Notes:
  # - "state" defaults to "present"
  #
  osx_defaults:
      - # disable saving to iCloud by default
        domain: "NSGlobalDomain"
        section: "NSDocumentSaveNewDocumentsToCloud"
        type: "-bool"
        value: "false"

      - # enable full keyboard access in dialogues
        domain: "NSGlobalDomain"
        section: "AppleKeyboardUIMode"
        type: "-int"
        value: "3"

      - # disable full-screen zoom animation
        domain: "NSGlobalDomain"
        section: "NSWindowResizeTime"
        type: "-float"
        value: "0.001"

      - # set highlight color to "Solarized yellow"
        # for calculation instructions, see http://dcmnt.me/1NqXTyq
        domain: "NSGlobalDomain"
        section: "AppleHighlightColor"
        type: "-string"
        value: "0.9921568627451 0.96470588235294 0.89019607843137"

      - # disable window opening / closing animations
        domain: "NSGlobalDomain"
        section: "NSAutomaticWindowAnimationsEnabled"
        type: "-bool"
        value: "false"

      - # disable feedback sound when changing volume
        domain: "NSGlobalDomain"
        section: "com.apple.sound.beep.feedback"
        type: "-bool"
        value: "false"

      - # show all file extensions
        domain: "NSGlobalDomain"
        section: "AppleShowAllExtensions"
        type: "-bool"
        value: "true"

      - # enable spring-loading for directories
        domain: "NSGlobalDomain"
        section: "com.apple.springing.enabled"
        type: "-bool"
        value: "true"

      - # remove spring-loading delay for directories
        domain: "NSGlobalDomain"
        section: "com.apple.springing.delay"
        type: "-float"
        value: "0"

      - # disable creation of .DS_Store on network volumes
        domain: "com.apple.desktopservices"
        section: "DSDontWriteNetworkStores"
        type: "-bool"
        value: "true"

      - # disable creation of .DS_Store on network volumes
        domain: "com.apple.loginwindow"
        section: "LoginwindowText"
        type: "-string"
        value: "If this Mac is found, please call +31 638 067 078 or email k.satirli@gmail.com"

      ###
      # Activity Monitor.app
      ###

      - # show main window
        domain: "com.apple.ActivityMonitor"
        section: "OpenMainWindow"
        type: "-bool"
        value: "true"

      - # show CPU usage in Dock icon
        domain: "com.apple.ActivityMonitor"
        section: "IconType"
        type: "-int"
        value: "5"

      - # show all processes
        domain: "com.apple.ActivityMonitor"
        section: "ShowCategory"
        type: "-int"
        value: "0"

      - # sort processes by CPU usage (1 of 2)
        domain: "com.apple.ActivityMonitor"
        section: "SortColumn"
        type: "-string"
        value: "CPUUsage"

      - # sort processes by CPU usage (2 of 2)
        domain: "com.apple.ActivityMonitor"
        section: "SortDirection"
        type: "-int"
        value: "0"

      ###
      # App Store.app
      ###

      - # enable debug menu for MAS
        domain: "com.apple.appstore"
        section: "ShowDebugMenu"
        type: "-bool"
        value: "true"

      ###
      # Calendar.app
      ###

      - # use System highlight color for Calendar
        domain: "com.apple.ical"
        section: "CalUIUseSystemHighlightColorForToday"
        type: "-bool"
        value: "true"


      ###
      # Crash Reporter.app
      ###

      - # disable Crash Reporter
        domain: "com.apple.CrashReporter"
        section: "DialogType"
        type: "-string"
        value: "none"

      ###
      # Disk Utility.app
      ###

      - # enable debug menu for Disk Utility
        domain: "com.apple.DiskUtility"
        section: "DUDebugMenuEnabled"
        type: "-bool"
        value: "true"

      ###
      # Dock.app
      ###

      - # auto-hide Dock
        domain: "com.apple.dock"
        section: "autohide"
        type: "-bool"
        value: "true"

      - # minimize windows into app icon
        domain: "com.apple.dock"
        section: "minimize-to-application"
        type: "-bool"
        value: "true"

      - # show indicators for open apps
        domain: "com.apple.dock"
        section: "show-process-indicators"
        type: "-bool"
        value: "true"

      - # enable screen-saver on bottom-left Hot Corner (1 of 2)
        domain: "com.apple.dock"
        section: "wvous-bl-corner"
        type: "-int"
        value: "5"

      - # enable screen-saver on bottom-left Hot Corner (2 of 2)
        domain: "com.apple.dock"
        section: "wvous-bl-modifier"
        type: "-int"
        value: "0"

      - # enable Notification Center on bottom-right Hot Corner (1 of 2)
        domain: "com.apple.dock"
        section: "wvous-br-corner"
        type: "-int"
        value: "12"

      - # enable Notification Center on bottom-right Hot Corner (2 of 2)
        domain: "com.apple.dock"
        section: "wvous-br-modifier"
        type: "-int"
        value: "0"

      - # set Dock icon size to 48 pixels
        domain: "com.apple.dock"
        section: "tilesize"
        type: "-int"
        value: "48"

      - # set Dock icons to translucent for hidden applications
        domain: "com.apple.dock"
        section: "showhidden"
        type: "-bool"
        value: "true"

      - # enable highlighting of grid view items
        domain: "com.apple.dock"
        section: "mouse-over-hilite-stack"
        type: "-bool"
        value: "true"

      - # disable Mission Control zoom effect
        domain: "com.apple.dock"
        section: "expose-animation-duration"
        type: "-int"
        value: "0"

      - # make Dock transparent
        domain: "com.apple.dock"
        section: "hide-mirror"
        type: "-bool"
        value: "true"

      - # add "Recent Applications" stack
        domain: "com.apple.dock"
        section: "persistent-others"
        type: "-array-add"
        value: "'{ 'tile-data' = { 'list-type' = 1; }; 'tile-type' = 'recents-tile'; }'"

      ###
      # Dashboard.app
      ###

      - # enable highlighting of grid view items
        domain: "com.apple.dashboard"
        section: "mcx-disabled"
        type: "-bool"
        value: "true"

      ###
      # Finder.app
      ###

      - # open new windows in home directory
        domain: "com.apple.finder"
        section: "NewWindowTargetPath"
        type: "-string"
        value: "\"file://$HOME\""

      - # disable "Go To Folder" option
        domain: "com.apple.finder"
        section: "ProhibitGoToFolder"
        type: "-bool"
        value: "true"

      - # open new window when removable media is mounted
        domain: "com.apple.finder"
        section: "OpenWindowForNewRemovableDisk"
        type: "-bool"
        value: "true"

      - # disable warning when changing file extension
        domain: "com.apple.finder"
        section: "FXEnableExtensionChangeWarning"
        type: "-bool"
        value: "false"

      - # show Path Bar
        domain: "com.apple.finder"
        section: "ShowPathbar"
        type: "-bool"
        value: "true"

      - # show Status Bar
        domain: "com.apple.finder"
        section: "ShowStatusBar"
        type: "-bool"
        value: "true"

      - # show external drives on Desktop
        domain: "com.apple.finder"
        section: "ShowExternalHardDrivesOnDesktop"
        type: "-bool"
        value: "true"

      - # show removable media on Desktop
        domain: "com.apple.finder"
        section: "ShowRemovableMediaOnDesktop"
        type: "-bool"
        value: "true"

      # - # hide harddisk from Sidebar
      #   domain: "com.apple.sidebarlists"
      #   section: "systemitems"
      #   subsection: "--dict-add ShowHardDisks"
      #   type: "-bool"
      #   value: "false"

      - # enable text selection in QuickLook
        domain: "com.apple.finder"
        section: "QLEnableTextSelection"
        type: "-bool"
        value: "true"

      - # enable secure-delete for Trash by default
        domain: "com.apple.finder"
        section: "EmptyTrashSecurely"
        type: "-bool"
        value: "true"

      - # expand File Info pane "General" by default
        domain: "com.apple.finder"
        section: "FXInfoPanesExpanded"
        subsection: "-dict General"
        type: "-bool"
        value: "true"

      - # expand File Info pane "Open With" by default
        domain: "com.apple.finder"
        section: "FXInfoPanesExpanded"
        subsection: "-dict OpenWith"
        type: "-bool"
        value: "true"

      - # expand File Info pane "Privileges" by default
        domain: "com.apple.finder"
        section: "FXInfoPanesExpanded"
        subsection: "-dict Privileges"
        type: "-bool"
        value: "true"

      - # hide "Tags" from Sidebar
        domain: "com.apple.finder"
        section: "ShowRecentTags"
        type: "-bool"
        value: "false"

      ###
      # Google Chrome
      ###

      - # expand print dialogue by default
        domain: "com.google.Chrome"
        section: "PMPrintingExpandedStateForPrint2"
        type: "-bool"
        value: "true"

      - # use the system-native print dialogue
        domain: "com.google.Chrome"
        section: "DisablePrintPreview"
        type: "-bool"
        value: "true"

      - # disable back-swipe with mouse
        domain: "com.google.Chrome"
        section: "AppleEnableMouseSwipeNavigateWithScrolls"
        type: "-bool"
        value: "false"

      - # disable back swipe with trackpad
        domain: "com.google.Chrome"
        section: "AppleEnableSwipeNavigateWithScrolls"
        type: "-bool"
        value: "false"

      ###
      # iTunes.app
      ###

      - # disable Home Sharing
        domain: "com.apple.itunes"
        section: "disableHomeSharing"
        type: "-bool"
        value: "true"

      ###
      # Messages.app
      ###

      - # disable Smart Quotes
        domain: "com.apple.messageshelper.MessageController"
        section: "SOInputLineSettings"
        subsection: -dict-add \"automaticQuoteSubstitutionEnabled\"
        type: "-bool"
        value: "false"

      ###
      # Safari.app
      ###

      - # don't send search queries to Apple (1 of 2)
        domain: "com.apple.Safari"
        section: "UniversalSearchEnabled"
        type: "-bool"
        value: "false"

      - # don't send search queries to Apple (2 of 2)
        domain: "com.apple.Safari"
        section: "SuppressSearchSuggestions"
        type: "-bool"
        value: "true"

      ###
      # Screensaver
      ###

      - # require password immediately after screensaver begins
        domain: "com.apple.screensaver"
        section: "askForPassword"
        type: "-int"
        value: "1"

      ###
      # Terminal.app
      ###

      - # use UTF-8 for Terminal
        domain: "com.apple.terminal"
        section: "StringEncodings"
        type: "-array"
        value: "4"

      ###
      # TextEdit.app
      ###

      - # set text-mode as default
        domain: "com.apple.TextEdit"
        section: "RichText"
        type: "-int"
        value: "0"

      - # save files as UTF-8 (1 of 2)
        domain: "com.apple.TextEdit"
        section: "PlainTextEncoding"
        type: "-int"
        value: "4"

      - # save files as UTF-8 (2 of 2)
        domain: "com.apple.TextEdit"
        section: "PlainTextEncodingForWrite"
        type: "-int"
        value: "0"

      ###
      # Time Machine.app
      ###

      - # no prompt for new drives
        domain: "com.apple.TimeMachine"
        section: "DoNotOfferNewDisksForBackup"
        type: "-bool"
        value: "true"

      ###
      # Universal Access
      ###

      - # use CTRL + mouse wheel to zoom in (1 of 2)
        domain: "com.apple.universalaccess"
        section: "closeViewScrollWheelToggle"
        type: "-bool"
        value: "true"

      - # use CTRL + mouse wheel to zoom in (2 of 2)
        domain: "com.apple.universalaccess"
        section: "HIDScrollZoomModifierMask"
        type: "-int"
        value: "262144"

      - # use CTRL + mouse wheel to zoom in (2 of 2)
        domain: "com.apple.universalaccess"
        section: "HIDScrollZoomModifierMask"
        type: "-int"
        value: "262144"

  osx_defaults_targets:
    - Dock
    - Finder
    - "Google Chrome"
    - Messages
    - Safari
    - SystemUIServer
