---
  atom_packages:
    # list packages you want to have installed here
      -
        name: editorconfig
        state: present
      # - # TODO: this module is not yet ready for production; use with caution
      #   name: language-ansible
      #   state: present
      -
        name: language-hosts
        state: present
      -
        name: language-terraform
        state: present
      -
        name: linter
        state: present
      -
        name: linter-js-yaml
        state: present
      -
        name: linter-jscs
        state: present
      -
        name: linter-jshint
        state: present
      -
        name: minimap
        state: present
      -
        name: minimap-find-and-replace
        state: present
      -
        name: minimap-linter
        state: present
      -
        name: minimap-selection
        state: present
      -
        name: seti-icons
        state: present

      # list packages you want to have uninstalled here
      -
        name: background-tips
        state: absent
      -
        name: base16-tomorrow-dark-theme
        state: absent
      -
        name: base16-tomorrow-light-theme
        state: absent
      -
        name: exception-reporting
        state: absent
      -
        name: language-clojure
        state: absent
      -
        name: language-csharp
        state: absent
      -
        name: metrics
        state: absent
      -
        name: package-generator
        state: absent
      -
        name: welcome
        state: absent
