---
  atom_packages:
    # list packages you want to have installed here
      -
        name: editorconfig
        state: install
      -
        name: language-hosts
        state: install
      -
        name: linter
        state: install
      -
        name: linter-js-yaml
        state: install
      -
        name: linter-jscs
        state: install
      -
        name: linter-jshint
        state: install
      -
        name: minimap
        state: install
      -
        name: minimap-selection
        state: install
