---
  #
  # list Homebrew Casks you want installed here.
  #
  homebrew_casks:
    -
      name: atom
    -
      name: caffeine
    -
      name: flux
    -
      name: google-chrome
    -
      name: gpgtools
    -
      name: virtualbox
    -
      name: vlc
