---
  #
  # list Homebrew Casks you want installed here.
  #
  homebrew_casks:
    -
      name: adium
    -
      name: adobe-creative-cloud
    -
      name: airfoil
    -
      name: amazon-workdocs
    -
      name: appium
    -
      name: arq
    -
      name: atext
    -
      name: atom
    -
      name: balsamiq-mockups
    -
      name: bartender
    -
      name: beaconscanner
    -
      name: bee
    -
      name: breakaway
    -
      name: caffeine
    -
      name: calibre
    -
      name: consul
    -
      name: consul-web-ui
    -
      name: docker-compose
    -
      name: docker-machine
    -
      name: dropbox
    -
      name: flux
    -
      name: garmin-express
    -
      name: google-chrome
    -
      name: google-earth-pro
    -
      name: gopro-studio
    -
      name: gpgtools
    -
      name: hipchat
    -
      name: kaleidoscope
    -
      name: knox
    -
      name: little-snitch
    -
      name: mitmproxy
    -
      name: openra
    -
      name: packer
    -
      name: plug
    -
      name: rdm
    -
      name: reflector
    -
      name: screenflow
    -
      name: sequel-pro
    -
      name: skim
    -
      name: slack
    -
      name: skype
    -
      name: steam
    -
      name: terraform
    -
      name: torbrowser
    -
      name: tower
    -
      name: vagrant
    -
      name: vault
    -
      name: virtualbox
    -
      name: vlc
