---

-
  name: Getting NPM Packages file
  stat:
    path: "{{ user_directory }}/npm-packages.yml"
  register: user_npm_packages

-
  name: Parsing NPM Package file
  include_vars: "{{ user_npm_packages.stat.path }}" # loads as `npm_packages`
  when: user_npm_packages.stat.exists

-
  name: install global NPM packages
  npm:
    name: "{{ item.name }}"
    global: true
    registry: "{{ item.registry | default('') }}"
    state: "{{ item.version | default('latest') }}"
    version: "{{ item.version | default('') }}"
  ignore_errors: true
  with_items: "{{ npm_packages.global }}"

-
  name: install global NPM packages
  gem:
    name: "{{ item.name }}"
    state: "{{ item.version | default('present') }}"
    version: "{{ item.version | default('latest') }}"
  ignore_errors: true
  with_items: "{{ npm_packages.global }}"
