---

-
  name: Place
  hosts: localhost
  strategy: free
  gather_facts: false

  tasks:
    -
      include: install-npm-packages.yml
      tags:
        - install-npm-packages

    -
      include: install-pip-packages.yml
      tags:
        - install-pip-packages

    -
      include: install-ruby-gems.yml
      tags:
        - install-ruby-gems

    -
      include: set-macos-defaults.yml
      tags:
        - set-macos-defaults

    -
      include: sync-dotfiles.yml
      tags:
        - sync-dotfiles
