---

-
  name: Getting pip packages file
  stat:
    path: "{{ user_directory }}/pip-packages.yml"
  register: user_pip_packages_file

- fail:
    msg: pip packages file does not exist at expected location
  when: user_pip_packages_file.stat.exists == false

-
  name: Parsing pip packages file
  include_vars: "{{ user_pip_packages_file.stat.path }}"
  when: user_pip_packages_file.stat.exists

-
  name: Installing pip packages
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default('') }}"
  ignore_errors: true
  with_items: "{{ pip_packages }}"
