---

-
  name: get list of desired NPM packages
  include_vars: "../config/users/{{ user }}/npm-packages.yml" # loads as `npm_packages`
  tags:
    - npm-install-packages

-
  name: install global NPM packages
  npm:
    name: "{{ item.name }}"
    global: true
    registry: "{{ item.registry | default('') }}"
    state: "{{ item.version | default('latest') }}"
    version: "{{ item.version | default('') }}"
  ignore_errors: true
  with_items: "{{ npm_packages.global }}"
  tags:
    - npm-install-packages
