---

-
  name: get list of desired Homebrew applications
  include_vars: "../config/users/{{ user }}/homebrew/applications.yml" # loads as `homebrew_applications`
  tags:
    - homebrew-install-applications

-
  name: install Homebrew applications
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default() }}"
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ config.homebrew.appdir }}"
  ignore_errors: true
  with_items: "{{ homebrew_applications }}"
  tags:
    - homebrew-install-applications
