---

-
  name: get list of desired PIP packages
  include_vars: "../config/users/{{ user }}/pip-packages.yml" # loads as `pip_packages`
  tags:
    - pip-install-packages

-
  name: install PIP packages
  become: true
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pip_packages }}"
  tags:
    - pip-install-packages
