---

-
  name: get list of desired OS X defaults
  include_vars: "../config/users/{{ user }}/osx-defaults.yml" # loads as `osx_defaults` and `osx_defaults_targets`
  tags:
    - osx-install-defaults

-
  name: set OS X defaults
  # NOTE: double-quotes allow for writing space-separated values (e.g.: 0 1 2) as a single entity (e.g.: "0 1 2")
  command: >
    defaults
      write
      {{ item.domain }}
      {{ item.section | default() }}
      {{ item.subsection | default() }}
      {{ item.type | default() }}
      {{ item.value }}
  with_items: "{{ osx_defaults }}"
  tags:
    - osx-install-defaults

-
  command: >
    killall "{{ item }}"
      > /dev/null
      2>&1
  ignore_errors: true
  with_items: "{{ osx_defaults_targets }}"
  tags:
    - osx-install-defaults
