---

-
  name: get list of desired Homebrew Casks
  include_vars: ../config/users/{{ user }}/homebrew/casks.yml # loads as `homebrew_casks`
  tags:
    - homebrew-install-casks

-
  name: install Homebrew Casks
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ config.homebrew.appdir }}"
  ignore_errors: true
  with_items: "{{ homebrew_casks }}"
  tags:
    - homebrew-install-casks
