---
-
  name: install Homebrew applications
  gather_facts: false
  hosts: localhost

  vars_files:
    - ../config/chair.yml # loads as `config`
    - ../config/user/homebrew/applications.yml # loads as `homebrew_applications`

  environment:
    HOMEBREW_GITHUB_API_TOKEN: "{{ config.env.HOMEBREW_GITHUB_API_TOKEN }}"

  tasks:
    -
      homebrew:
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{ item.install_options | default() }}
      environment:
        HOMEBREW_CASK_OPTS: --appdir=/Applications
      with_items: "{{ homebrew_applications }}"
