---

-
  name: building your Chair
  hosts: localhost
  strategy: free
  gather_facts: true

  vars_files:
    - "../config/chair.yml" # loads as `config`
    - "../config/users/{{ user }}/my_chair.yml" # loads as `user_config`

  tasks:
    # Homebrew: CLI applications
    - stat:
        path: "./config/users/{{ user }}/homebrew/applications.yml"
      register: user_applications

    -
      include: install-homebrew-applications.yml
      when: user_applications.stat.exists

    # Homebrew: GUI applications
    - stat:
        path: "./config/users/{{ user }}/homebrew/casks.yml"
      register: user_casks

    -
      include: install-homebrew-casks.yml
      when: user_casks.stat.exists

    # PIP: Packages
    - stat:
        path: "./config/users/{{ user }}/pip-packages.yml"
      register: user_pip_packages

    -
      include: install-pip-packages.yml
      when: user_pip_packages.stat.exists

    # Atom: Packages
    - stat:
        path: "./config/users/{{ user }}/atom-packages.yml"
      register: user_atom_packages

    -
      include: install-atom-packages.yml
      when: user_atom_packages.stat.exists

    # NPM: Packages
    - stat:
        path: "./config/users/{{ user }}/npm-packages.yml"
      register: user_npm_packages

    -
      include: install-npm-packages.yml
      when: user_npm_packages.stat.exists

    # OS X: defaults
    - stat:
        path: "./config/users/{{ user }}/osx-defaults.yml"
      register: user_osx_defaults

    -
      include: install-osx-defaults.yml
      when: user_osx_defaults.stat.exists
