---
  #
  # list Node modules you want installed (globally) here.
  #
  # Example:
  # -
  #   name: virgilio
  #   version: 1.2.3
  #   registry: https://registry.acme.com
  #
  # Notes:
  # - "version" defaults to "latest"
  # - "registry" defaults to the npmjs.org registry
  #
  npm_packages:
    global:
      -
        name: grunt
        version: latest
