---
  #
  # list PIP packages you want installed (globally) here.
  #
  # Example:
  # -
  #   name: pylint
  #   state: present
  #
  # Notes:
  # - "state" defaults to "present"
  #
  pip_packages:
      -
        name: pylint
